spring:
  data:
    redis:
      port: 6379
      host: localhost
      channel:
        follower: follower_channel
        achievement: achievement_channel

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com #https://www.baeldung.com/spring-email
    password: whatever #https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=638195765566773400-3814427644
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
    host: localhost
    port: 8082
user-service:
    host: localhost
    port: 8080
telegram:
  bot:
    token: "6436403091:AAFdLcAUzM4WTwV3MS65-J03LpkBmOEkmPc"
    name: "NotifyX bot"