spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  data:
    redis:
      port: 6379
      host: localhost
      channels:
        follower: follower-channel
        achievement: achievement-channel
        skill_offer_channel: skill-offer-channel
        recommendation_requested_event_channel: recommendation-requested-event-channel
        mentorship_accepted_request_event_channel: mentorship-accepted-request-event-channel
        like_channel: like-channel

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com #https://www.baeldung.com/spring-email
    password: whatever #https://support.google.com/mail/answer/7104828?hl=en&rd=3&visit_id=638195765566773400-3814427644
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  messages:
    basename: messages

config:
  import: classpath:messages/messages_ru.yaml

server:
  port: 8083

logging:
  level:
    root: info

#Можно зарегистрировать аккаунт без привязки карты. Будет 2 евро на отправку тестовых SMS
vonage: #https://dashboard.nexmo.com/getting-started/sms
  api:
    key: whatever
    secret: whatever

project-service:
    host: localhost
    port: 8082
user-service:
    host: localhost
    port: 8080

telegram-bot:
    token: 6380435511:AAEyzza7N9D8jxiZ6-Wm7nqCiZhhXHwrzAU
    name: CorporationXWerewolfBot

